### PR TITLE
Handle cases where depths appear multiple times

### PR DESCRIPTION
**Pull request by polpo**
Fix for Issue #79.

### CODE REVIEW

**Comment by sidorares** [comment]
maybe just have a counter for number of deserialized depths instead of checking number of keys (adjusted with your change)? So instead of `if (Object.keys(depths).length == n_depths)` do `if (numParsedDepth == n_depths) { ... } `

**Comment by sidorares** [comment]
@santigimeno can you look at this as well?

**Comment by polpo** [comment]
I could keep a counter of the deserialized depths, but I'll have to pass the counter as one of the arguments to readDepths because it's called recursively. Not sure if that's cleaner than decrementing n_depths.

**Comment by sidorares** [comment]
you could have it in a closure, not as a parameter

**Comment by santigimeno** [comment]
I would also do as @sidorares suggests. 
Apart from that it would be great having a test for this. Maybe making lib/xserver.js to send the same response tigerVNC is sending. Would this be feasible @sidorares ?

**Comment by sidorares** [comment]
Yep, I'll try to make server available as test helper ( would be great to have all handshake logic covered with tests )

**Comment by polpo** [comment]
Ok, I've refactored to use a counter. I moved `readDepths()` into `readScreens()` so I could keep `numParsedDepths` in a closure.

Tested with multiple screens (Xdmx + two TigerVNC Xvnc servers) and everything seems to behave properly.

**Comment by sidorares** [comment]
Looks good to me! I'll leave this open until I add fake server helper to test PR's like this

**Comment by polpo** [comment]
Know what it'd take to merge this?

**Comment by sidorares** [comment]
@polpo I can merge this and we'll have fake server & tests later. Can you rebase first?

**Comment by polpo** [comment]
Hmm. I rebased and Travis is now failing for this PR. It passed in my own repository (https://travis-ci.org/Arteris/node-x11/builds/130971542) so I am not sure what is going wrong here.

**Comment by sidorares** [comment]
hi @polpo  - I added you as a collaborator, I think Travis access mirrors github rules so you should be able to see errors or restart builds

**Comment by sidorares** [comment]
This test fails randomly:

```
  1) KillKlient request "before each" hook:
     Error: Bad param value
      at ReadFixedRequest.callback (lib/xcore.js:440:29)
      at ReadFixedRequest.execute (lib/unpackstream.js:41:10)
      at UnpackStream.resume (lib/unpackstream.js:165:30)
      at UnpackStream.write (lib/unpackstream.js:102:10)
      at Socket.<anonymous> (lib/xcore.js:70:21)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
  2) KillKlient request should terminate other client connection:
     Error: timeout of 80000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by sidorares** [comment]
I restarted failing tests manually and it's all green now but we need to look at that test some time soon

**Pull request merged**
