### PR TITLE
Cache X11 extensions

### PR DESCRIPTION
**Pull request by santigimeno**

### CODE REVIEW

**Comment by sidorares** [comment]
👍

**Comment by santigimeno** [comment]
@sidorares Thanks!  do you mind if I publish `2.1.1`?

**Comment by sidorares** [comment]
sure, please do publish! 
ps one of the tests ( kill client ) is flaky, would be good to figure out why - I had to re-run couple of jobs

**Comment by santigimeno** [comment]
Thanks, I'll do it now.
I saw the flakiness myself, will look into it afterwards.

**Pull request merged**
