### PR TITLE
Fall back to TCP if socket does not exist

### LINKED ISSUE #94: createClient should fall back to TCP if Unix socket does not exist
Xlib and XCB fall back to using TCP on localhost if the Unix socket does not exist. node-x11 should do the same. 

We've run into a few instances with users whose /tmp/.X11-unix/X* socket file has been deleted out from under them, but their X session appears to continue to work due to Xlib and XCB's falling back.

### PR DESCRIPTION
**Pull request by polpo**
Also have client emit error on stream error if there is no initCb.

Fixes #94.

### CODE REVIEW

**Comment by polpo** [comment]
BTW, this can be tested by launching an Xvfb or Xephyr with `-nolisten unix` and setting `DISPLAY` with no hostname.

**Comment by sidorares** [comment]
do you think this test can be added somehow to travis?

**Comment by polpo** [comment]
I think so. It looks like it's possible to manually start Xvfb with custom options on Travis ([seen here](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Configuring-xvfb-screen-size-and-more)).

**Comment by sidorares** [comment]
would be good to add if possible, if not easy - LGTM as is

**Comment by polpo** [comment]
I'll try to get a Travis configuration working that tests both normal and fallback scenarios.

**Comment by polpo** [comment]
I've added an updated .travis.yml that does two tests, one with -nolisten tcp, and one with -nolisten unix.

**Pull request merged**
