### PR TITLE
Adds Shape extension request Rectangles; fixes Mask

### PR DESCRIPTION
**Pull request by megadonkey**
This change to ext/shape.js adds request Rectangles, and fixes Mask.
I also commented out captureMask() calls for now, because those break everything, not sure what's going on there.

### CODE REVIEW

**Comment by megadonkey** [comment]
Err, "captureStack()"

**Comment by sidorares** [comment]
captureStack is called only if debug set to true. Do you see problems even without debug flag set?

**Comment by sidorares** [comment]
oh, it's only in Shape. Do you have any tests/examples? put anything you used to see if things work under examples/smoketest

**Comment by megadonkey** [comment]
Rectangles works, added an example of that. Also fixed existing smoketest (that sets a shape mask), it now successful.

**Comment by sidorares** [comment]
thanks, merging!

**Pull request merged**
